server:
  port: 9091
  address: 0.0.0.0

  ip: localhost
# \u6570\u636E\u5E93\u914D\u7F6E
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: han
    password: 123456789
    url: jdbc:mysql://8.140.229.104:3306/han?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# \u914D\u7F6Emybatis\u5B9E\u4F53\u548Cxml\u6620\u5C04
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

  mapper-locations: classpath:mapper/*.xml
